export const langSet = {
  en_US: {
    SITE_TITLE: `DDK Map`,
    MAP_LOADING_DATA: `Loading map data`,
    MAP_UI_POWERED_BY: `© diversitydatakids.org`,
    MAP_AUTHOR: `diversitydatakids.org`,
    SITE_DESCRIPTION: `Exploratory map developed by diversitydatakids.org`,
    SITE_KEYWORDS: `child, opportunity, measure, index, metric, health, social, economic, education, national, state, metro`,
    MAP_TEST_MERGE_EXTRA: `Test`,
    SHARE: 'Share',
    BUTTON_SHARE_TWITTER: 'Share on Twitter',
    DIALOG_SHARE_TWITTER: 'share text', // TODO
    BUTTON_SHARE_FACEBOOK: 'Share on Facebook',
    DIALOG_SHARE_FACEBOOK: 'share text', // TODO
    BUTTON_SHARE_EMAIL: 'Share via email',
    DIALOG_SHARE_EMAIL: 'share text', // TODO
    BUTTON_SHARE_LINK: 'Get a custom link',
    DIALOG_SHARE_LINK: 'share text', // TODO
    MODAL_SHARE_LINK_HEAD: 'Share a Link',
    MODAL_SHARE_LINK_INSTR:
      'Copy the link below to share the current view of the Explorer.',
    MODAL_SHARE_LINK_INPUT: 'Current View URL',
    BUTTON_SHARE_EMBED: 'Embed this map',
    DIALOG_SHARE_EMBED: 'share text', // TODO
    MODAL_SHARE_EMBED_HEAD: 'Embed this map',
    MODAL_SHARE_EMBED_INSTR:
      'Use the code below to embed the map on your website. The map will match your current map view and selections in the explorer.',
    MODAL_SHARE_EMBED_INPUT: 'Map Embed Code',
    UNIT_MCM: '&#181;g/m&#0179;',
    UNIT_MCM_DESC: `Micrograms per cubic meter`,
    UNIT_PPB: 'ppb',
    UNIT_PPB_DESC: 'Parts per billion',
    POPUP_CENSUS_TRACT: `Census tract ID: {id}`,
    POPUP_POPULATION: `Child population (0-17) by race/ethnicity`,
    POP_W: `White`,
    POP_AI: `AI/AN`,
    POP_AP: `Asian/PI`,
    POP_HI: `Hispanic`,
    POP_B: `Black`,
    NATION: `nation`,
    STATE: `state`,
    METRO: `metro area`,
    POPUP_DEMO_POP: `{demo}: {pop}`,
    SDSCALE_VLOW: `very low`,
    SDSCALE_LOW: `low`,
    SDSCALE_MOD: `moderate`,
    SDSCALE_HIGH: `high`,
    SDSCALE_VHIGH: `very high`,
    SLIDEOUT_COMPARING_TO: `<b>Compared to:</b> other neighborhoods in {normPhrase}`,
    POPUP_COMPARED_TO: `Compared to {normPhrase}`,
    SLIDEOUT_NEIGHBORHOODS_IN: `other neighborhoods in {normPhrase}`,
    SLIDEOUT_THIS_METRO: `this metro area`,
    SLIDEOUT_THIS_STATE: `this state`,
    SLIDEOUT_THIS_NAT: `the nation`,
    LEGEND_M: `Metro`,
    LEGEND_S: `State`,
    LEGEND_N: `National`,
    LEGEND_10: `2010`,
    LEGEND_15: `2015`,
    LEGEND_XC: `Childhood Opportunity Levels, Overall COI`,
    LEGEND_XO: `Childhood Opportunity Levels, Social and Economic Domain`,
    LEGEND_XE: `Childhood Opportunity Levels, Education Domain`,
    LEGEND_XH: `Childhood Opportunity Levels, Health and Environment Domain`,
    LEGEND_CHART_TOGGLE_ON: `SHOW CHART`,
    LEGEND_CHART_TOGGLE_OFF: `HIDE CHART`,
    LEGEND_SELECT_INDEX: `Select an Index:`,
    LEGEND_COMPARE: `Compare To:`,
    LEGEND_TIME: `Time Period:`,
    LEGEND_DEMO: `Select a Race/Ethnicity:`,
    LEGEND_CHART_TITLE: `Percentage of Children at Each Opportunity Level`,
    LEGEND_CHART_SUBTITLE: `By race/ethnicity for {chartSubtitle}`,
    LEGEND_CONTROL_TRUE: `HIDE CONTROLS`,
    LEGEND_CONTROL_FALSE: `SHOW CONTROLS`,
    SLIDEOUT_COMPARE_TIP: `Your location is being compared to others in {normPhrase}. Use the “Compare to” dropdown to change this.`,
    SLIDEOUT_TIP_COI: `<b>Child Opportunity Index</b> is an index of neighborhood resources and conditions that help children develop in a healthy way. It combines data from 29 neighborhood-level indicators into a single composite measure.`,
    SLIDEOUT_TIP_XO: `<b>Social and Economic Index</b> combines poverty rate, public assistance rate, homeownership rate, high skill employment, and median household income, transformed to z-scores.`,
    SLIDEOUT_TIP_XH: `<b>Health and Environment Index</b> combines healthy environment, toxic exposure, and health resource indicators. `,
    SLIDEOUT_TIP_XE: `<b>Education Index</b> combines Early childhood education, Elementary education, Secondary and postsecondary education, and Educational and social resources indicators. `,
    SEARCH_PROMPT: `Search for a location (address, city, or state)`,
    BTN_SEARCH: `Search`,
    BTN_SHOW_ALL: `SHOW ALL`,
    BTN_HIDE_ALL: `HIDE ALL`,
    SCALE_MEAN: `Mean`,
    SCALE_INDICATORS_SHOW: `Show indicators`,
    SCALE_INDICATORS_HIDE: `Hide indicators`,
    LABEL_XC: `Overall Child Opportunity`,
    LABEL_XH: `Health & Environment`,
    LABEL_XO: `Social & Economic`,
    LABEL_XE: `Education`,
    BTN_MENU: `Menu`,
    POPUP_CLICK_PROMPT: `Click the census tract for location details.`,
    POPUP_ZOOM_PROMPT: `Double-click to zoom in and see tract data.`,
    POPUP_METRO_PROMPT: `Click a metro area to explore the tracts.`,
    WARN_METRO_COMPARISON: `Your location is being compared to others in the metro area. To make comparisons across metro areas switch to state or national norming.`,
    WARN_STATE_COMPARISON: `Your location is being compared to others in the state. To make comparisons across states switch to national norming.`,
    WARN_NATL_COMPARISON: `Your location is being compared to others across the nation.`,
    MAP_FLY_TO_STATE: `Fly to {state}`,
    MAP_RESET: `Reset map viewport`,
    MAP_FLY_TO_MY: `Fly to my location`,
  },
}
