export const langSet = {
  en_US: {
    SITE_TITLE: `DDK Map`,
    MAP_LOADING_DATA: `Loading map data`,
    MAP_UI_POWERED_BY: `© diversitydatakids.org`,
    MAP_AUTHOR: `diversitydatakids.org`,
    SITE_DESCRIPTION: `Exploratory map developed by diversitydatakids.org`,
    SITE_KEYWORDS: `child, opportunity, measure, index, metric, health, social, economic, education, national, state, metro`,
    MAP_TEST_MERGE_EXTRA: `Test`,
    SHARE: 'Share',
    BUTTON_SHARE_TWITTER: 'Share on Twitter',
    DIALOG_SHARE_TWITTER: 'share text', // TODO
    BUTTON_SHARE_FACEBOOK: 'Share on Facebook',
    DIALOG_SHARE_FACEBOOK: 'share text', // TODO
    BUTTON_SHARE_EMAIL: 'Share via email',
    DIALOG_SHARE_EMAIL: 'share text', // TODO
    BUTTON_SHARE_LINK: 'Get a custom link',
    DIALOG_SHARE_LINK: 'share text', // TODO
    MODAL_SHARE_LINK_HEAD: 'Share a Link',
    MODAL_SHARE_LINK_INSTR:
      'Copy the link below to share the current view of the Explorer.',
    MODAL_SHARE_LINK_INPUT: 'Current page link',
    BUTTON_SHARE_EMBED: 'Embed this map',
    DIALOG_SHARE_EMBED: 'share text', // TODO
    MODAL_SHARE_EMBED_HEAD: 'Embed this map',
    MODAL_SHARE_EMBED_INSTR:
      'Use the code below to embed the map on your website. The map will match your current map view and selections in the explorer.',
    MODAL_SHARE_EMBED_INPUT: 'Embed code',
    UNIT_MCM: '&#181;g/m&#0179;',
    UNIT_MCM_DESC: `Micrograms per cubic meter`,
    UNIT_PPB: 'ppb',
    UNIT_PPB_DESC: 'Parts per billion',
    POPUP_CENSUS_TRACT: `Census tract ID: {id}`,
    POPUP_POPULATION: `Child population (0-17) by race/ethnicity`,
    POP_W: `White`,
    POP_AI: `AI/AN`,
    POP_AP: `Asian/PI`,
    POP_HI: `Hispanic`,
    POP_B: `Black`,
    NATION: `nation`,
    STATE: `state`,
    METRO: `metro area`,
    POPUP_DEMO_POP: `{demo}: {pop}`,
    SDSCALE_VLOW: `very low`,
    SDSCALE_LOW: `low`,
    SDSCALE_MOD: `moderate`,
    SDSCALE_HIGH: `high`,
    SDSCALE_VHIGH: `very high`,
    SLIDEOUT_COMPARING_TO: `<b>Compared to:</b> other neighborhoods in {normPhrase}`,
    POPUP_COMPARED_TO: `Compared to {normPhrase}`,
    SLIDEOUT_NEIGHBORHOODS_IN: `other neighborhoods in {normPhrase}`,
    SLIDEOUT_THIS_METRO: `this metro area`,
    SLIDEOUT_THIS_STATE: `this state`,
    SLIDEOUT_THIS_NAT: `the nation`,
    LEGEND_M: `Metro`,
    LEGEND_S: `State`,
    LEGEND_N: `National`,
    LEGEND_10: `2010`,
    LEGEND_15: `2015`,
    LEGEND_XC: `Childhood Opportunity Levels, Overall COI`,
    LEGEND_XO: `Childhood Opportunity Levels, Social and Economic Domain`,
    LEGEND_XE: `Childhood Opportunity Levels, Education Domain`,
    LEGEND_XH: `Childhood Opportunity Levels, Health and Environment Domain`,
    LEGEND_CHART_TOGGLE_ON: `SHOW CHART`,
    LEGEND_CHART_TOGGLE_OFF: `HIDE CHART`,
    LEGEND_SELECT_INDEX: `Select an Index:`,
    LEGEND_COMPARE: `Compare To:`,
    LEGEND_TIME: `Time Period:`,
    LEGEND_DEMO: `Select a Race/Ethnicity:`,
    LEGEND_CHART_TITLE: `Percentage of Children at Each Opportunity Level`,
    LEGEND_CHART_SUBTITLE: `By race/ethnicity for {chartSubtitle}`,
    LEGEND_CONTROL_TRUE: `HIDE CONTROLS`,
    LEGEND_CONTROL_FALSE: `SHOW CONTROLS`,
    SLIDEOUT_COMPARE_TIP: `Your location is being compared to others in {normPhrase}. Use the “Compare to” dropdown to change this.`,
    SLIDEOUT_TIP_COI: `<b>Child Opportunity Index</b> is an index of neighborhood resources and conditions that help children develop in a healthy way. It combines data from 29 neighborhood-level indicators into a single composite measure.`,
    SLIDEOUT_TIP_XO: `<b>Social and Economic Index</b> combines poverty rate, public assistance rate, homeownership rate, high skill employment, and median household income, transformed to z-scores.`,
    SLIDEOUT_TIP_XH: `<b>Health and Environment Index</b> combines healthy environment, toxic exposure, and health resource indicators. `,
    SLIDEOUT_TIP_XE: `<b>Education Index</b> combines Early childhood education, Elementary education, Secondary and postsecondary education, and Educational and social resources indicators. `,
    SEARCH_PROMPT: `Search for a location (address, city, or state)`,
    BTN_SEARCH: `Search`,
    BTN_SHOW_ALL: `SHOW ALL`,
    BTN_HIDE_ALL: `HIDE ALL`,
    SCALE_MEAN: `Mean`,
    SCALE_INDICATORS_SHOW: `Show indicators`,
    SCALE_INDICATORS_HIDE: `Hide indicators`,
    LABEL_XC: `Overall Child Opportunity`,
    LABEL_XH: `Health & Environment`,
    LABEL_XO: `Social & Economic`,
    LABEL_XE: `Education`,
    BTN_MENU: `Menu`,
    POPUP_CLICK_PROMPT: `Click the census tract for location details.`,
    POPUP_ZOOM_PROMPT: `Double-click to zoom in and see tract data.`,
    POPUP_METRO_PROMPT: `Click a metro area to explore the tracts.`,
    WARN_METRO_NORM_GENERIC: `Your location is being compared to others in the metro area. To make comparisons across metro areas switch to state or national norming.`,
    WARN_METRO_NORM: `Your location is being compared to others in the {metro}. To make comparisons across metro areas switch to state or national norming.`,
    WARN_STATE_NORM_GENERIC: `Your location is being compared to others in the state. To make comparisons across states switch to national norming.`,
    WARN_STATE_NORM: `Your location is being compared to others in {state}. To make comparisons across states switch to national norming.`,
    WARN_NATL_NORM: `Your location is being compared to others across the nation.`,
    PANEL_FAQ_TITLE: `Frequently asked questions`,
    FAQ: [
      {
        title: 'How can I use this information?',
        content:
          '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p><p>Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>',
      },
      {
        title: 'Where does this information come from?',
        content:
          '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p><p>Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>',
      },
      {
        title:
          'How can I choose between metro-normed, state-normed, and nationally-normed data?',
        content:
          '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p><p>Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>',
      },
    ],
    MAP_FLY_TO_STATE: `Fly to {state}`,
    MAP_RESET: `Reset map viewport`,
    MAP_FLY_TO_MY: `Fly to my location`,
    MAP_SCREENSHOT: `Take a screenshot of the map`,
    MODAL_INTRO_HEADING: `Child Opportunity Map`,
    MODAL_INTRO_DESC: `The map and charts in this tool provide a visualization of several indices, including Overall Child Opportunity Index, Social and Economic Index, Health and Environment Index, and Education Index.`,
    MODAL_INTRO_PROMPT: ` Get started:`,
    MODAL_INTRO_GO_TO: ` Go to my location`,
    MODAL_INTRO_NAT: ` See the national map`,
    MODAL_INTRO_FAQ: ` Read FAQs`,
    MODAL_INTRO_SEARCH: `Search for an address, city, or state`,
    LEGEND_NORM_HELP: `This data can only be compared to other neighborhoods in this metro area. See FAQ for more information.`,
    LEGEND_TOOLTIP_LABEL: `Show data on hover`,
    MENU_CLOSE: `Close menu`,
    MENU: [
      [
        {
          label: `Early Childhood`,
          link: `https://www.diversitydatakids.org/early-childhood`,
          active: 0,
        },
        {
          label: `Income, Work and Family`,
          link: `https://www.diversitydatakids.org/income-work-and-family`,
          active: 0,
        },
        {
          label: `Neighborhoods`,
          link: `https://www.diversitydatakids.org/neighborhoods`,
          active: 0,
        },
      ],
      [
        {
          label: `Datasets`,
          link: `https://data.diversitydatakids.org/dataset?_ga=2.118586825.1559503741.1614712999-1749705169.1612460726`,
          active: 0,
        },
        {
          label: `Child Opportunity Index`,
          link: `https://www.diversitydatakids.org/child-opportunity-index`,
          active: 0,
        },
        {
          label: `Policy Equity Assessments`,
          link: `https://www.diversitydatakids.org/policy-equity-assessments`,
          active: 0,
        },
      ],
      [
        {
          label: `Menu`,
          link: `https://www.diversitydatakids.org/about-us`,
          active: 1,
        },
        {
          label: `About Us`,
          link: `https://www.diversitydatakids.org/about-us`,
          active: 0,
        },
        {
          label: `FAQs`,
          link: `https://www.diversitydatakids.org/research-library/frequently-asked-questions`,
          active: 0,
        },
        {
          label: `Impact Stories`,
          link: `https://www.diversitydatakids.org/impact-stories`,
          active: 0,
        },
        {
          label: `News`,
          link: `https://www.diversitydatakids.org/news`,
          active: 0,
        },
        {
          label: `Contact Us`,
          link: `https://www.diversitydatakids.org/contact-us`,
          active: 0,
        },
      ],
    ],
    CONTROL_PANEL_SHARE: `Share`,
    CONTROL_PANEL_LOCATION: `Location<br />Details`,
    CONTROL_PANEL_FAQS: `FAQs`,
  },
}
